name: CI
on:
  pull_request_review:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
    - id: comment_body
      uses: Khan/pull-request-comment-trigger@master
      with:
        trigger: "review"
    - run: |
        echo ${{steps.comment_body.outputs.comment_body}} 
