name: Discussion Workflow Run

on:
  workflow_run:
    workflows: ["Discussion"]
    types:
      - completed
    
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: souragc/myaction@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
