name: OSP Director Operator image builder

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - .gitignore
      - .pull_request_pipeline
      - changelog.txt
      - kuttl-test.yaml
      - LICENSE
      - Makefile
      - OWNERS
      - PROJECT
      - README.md
      - .github/
      - build/
      - docs/
      - tests/

env:
  imageregistry: 'quay.io'
  imagenamespace: 'openstack-k8s-operators'
  latesttag: latest

jobs:
  build-osp-director-operator:
    name: Build osp-director-operator image using buildah
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: haa
      run: |
        echo ${{ github.head_ref }}
        echo ${{ github.base_ref }}

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5

    - name: Set latest tag for non master branch
      if: "${{ steps.branch-name.outputs.current_branch != 'master' }}"
      run: |
        echo "latesttag=${{ steps.branch-name.outputs.current_branch }}-latest" >> $GITHUB_ENV
