name: OSP Director Operator image builder

on:
  push:
    branches:
      - '*'

jobs:
  main_test:
    runs-on: ubuntu-latest
    steps:
      - uses: souragc/myaction@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
