name: testing patch

on:
  issue_comment:
  
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.comment.body }}"
        env:
          BODY: ${{ github.event.comment.body }}
      - uses: actions/checkout@v2
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
