name: testing patch

on:
  issue_comment:
  
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${UPDATE_COMPONENT}"
        env:
          BODY: ${{ github.event.comment.body }}
